### ISSUE TITLE
Both IPlayer.IListener And IPlayer.IAnalyticsListener AbstractMethodError 

### ISSUE THREAD

**Issue by doughouzlight** [Baseflow/ExoPlayerXamarin#138] opened 2022-11-15 08:10 UTC
## 🐛 Bug Report

In the latest version of ExoPlayer 2.18.3, the IPlayer.IListener interface causes a crash.

Player crashes with this stack trace:

```
java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$IListener .onTimelineChanged(com.google.android.exoplayer2.Timeline, int)"
at crc64c7906c01a42d8080.DroidEventLogger.n_onTimelineChanged(Native Method)
at crc64c7906c01a42d8080.DroidEventLogger.onTimelineChanged(DroidEventLogger.java:162)
at 
```

After commenting it on your xml binding there is other range of errors such onisLoading and etc ... 

### Expected behavior

Should work as its the most important function of the player

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :robot: Android

**Comment by ArchangelWTF** [comment] 2022-11-15 17:23
Mostly a duplicate of https://github.com/Baseflow/ExoPlayerXamarin/issues/137

**Closed** 2022-12-08 13:35 UTC
