### ISSUE TITLE
System.TypeInitializationException with IPlayerEventListener

### ISSUE THREAD

**Issue by MagneticLlama** [Baseflow/ExoPlayerXamarin#114] opened 2020-10-02 02:25 UTC
## 🐛 Bug Report

I have a class that implements IPlayerEventListener, and an exception occurs when the class is constructed.
`System.TypeInitializationException: 'The type initializer for 'Com.Google.Android.Exoplayer2.IPlayerEventListener' threw an exception.'`

```
10-01 21:18:29.561 I/MonoDroid(19692): UNHANDLED EXCEPTION:
10-01 21:18:29.564 I/MonoDroid(19692): System.TypeInitializationException: The type initializer for 'Com.Google.Android.Exoplayer2.IPlayerEventListener' threw an exception. ---> System.MissingMethodException: Method not found: void Android.Runtime.XAPeerMembers..ctor(string,System.Type,bool)
10-01 21:18:29.564 I/MonoDroid(19692):    --- End of inner exception stack trace ---
10-01 21:18:29.564 I/MonoDroid(19692):   at Android.Runtime.AndroidTypeManager.RegisterNativeMembers (Java.Interop.JniType jniType, System.Type type, System.String methods) [0x00137] in <07ae79e8d8f94e5fa94a23fe57b46db3>:0 
10-01 21:18:29.564 I/MonoDroid(19692):   at Android.Runtime.JNIEnv.RegisterJniNatives (System.IntPtr typeName_ptr, System.Int32 typeName_len, System.IntPtr jniClass, System.IntPtr methods_ptr, System.Int32 methods_len) [0x00115] in <07ae79e8d8f94e5fa94a23fe57b46db3>:0 
10-01 21:18:29.564 I/MonoDroid(19692):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_alloc_object(intptr,intptr&,intptr)
10-01 21:18:29.564 I/MonoDroid(19692):   at Java.Interop.JniEnvironment+Object.AllocObject (Java.Interop.JniObjectReference type) [0x00027] in <42bcf67b56bc4c909c2a5edee682522b>:0 
10-01 21:18:29.564 I/MonoDroid(19692):   at Java.Interop.JniType.AllocObject () [0x0000c] in <42bcf67b56bc4c909c2a5edee682522b>:0 
10-01 21:18:29.564 I/MonoDroid(19692):   at Java.Interop.JniPeerMembers+JniInstanceMethods.StartCreateInstance (System.String constructorSignature, System.Type declaringType, Java.Interop.JniArgumentValue* parameters) [0x00044] in <42bcf67b56bc4c909c2a5edee682522b>:0 
```
Using this interface works properly on versions prior to 2.11.

### Configuration

**Version:** 2.11 (any)
**Dex Compiler:** d8

**Comment by martijn00** [comment] 2020-10-02 08:16
Duplicate of https://github.com/Baseflow/ExoPlayerXamarin/issues/112#issuecomment-697360932

**Closed by martijn00** 2020-10-02 08:16 UTC

**Comment by MagneticLlama** [comment] 2020-10-02 16:18
I already have the interface methods mentioned in that other post in place. That didn't resolve this issue.
